/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./components/Card/Card.vue')['default']
    Context: typeof import('./components/Markdown/Context.vue')['default']
    Divider: typeof import('./components/Divider/Divider.vue')['default']
    Footer: typeof import('./components/Footer/Footer.vue')['default']
    LNav: typeof import('./components/Nav/LNav.vue')['default']
    RNav: typeof import('./components/Nav/RNav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/Search/Search.vue')['default']
    SearchCell: typeof import('./components/Search/SearchCell.vue')['default']
    Swiper: typeof import('./components/Swiper/Swiper.vue')['default']
    SwiperItem: typeof import('./components/Swiper/SwiperItem.vue')['default']
  }
}
